name: Lint Commit
on: [ push, pull_request ]
defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies with pnpm
        run: pnpm install

      - name: Lint Commit Message
        run: pnpm run lint check commit

