name: Release
on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  analyze:
    name: Analyze
    uses: ./.github/workflows/codeql-analysis.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  release:
    name: Make a Release
    needs: [ ci, analyze ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download compiled files
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Prepare pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release